### ISSUE TITLE
Prevent server crash when request/response object throws error 

### ISSUE THREAD

**Issue by lodeme** [ddavlet/webserv#9]
**Issue**: With the new exceptions in the Request object, if one is triggered it will bring down the whole server. 

**Proposed solution** When it is called in the server object, encapsulate the requests and response calls within a try/catch block to prevent full server crash

**Comment by lodeme** [comment]
This makes sense, but I feel like if we log all the errors that we catch, we can also ensure the control flow of the program without breaking functionality.

Also, when we encounter errors we may want to create a test file related to it that would ensure that this issue does not reappear in later versions of the program.

In short: we can have a basic CI/CD pipeline in place

**Comment by ddavlet** [comment]
I think it depends on what part we currently working on. Since I work mostly in changing current code, adding small features, I see space for improvement and bug fixes with every "crush" of exceptions. It helps me to keep track of how it should respond in certain cases. If we will add try-catch now, we may miss some crucial steps when exception occurred. 

What you think if we add them only in case if it stops from developing project further or stash those changes to save temporary try-catch locally.
